### ISSUE TITLE
Server returned a status code of 403 while downloading

### ISSUE THREAD

**Issue by kaz875** [ading2210/poe-api#158]
I received these errors upon initialting client = poe.Client(...)

WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (4/10)..

Retries till 10/10 and then it gave up. Is this unofficial API stop working now after some change on Poe side?

**Comment by wangyu1997** [comment]
me too.

**Comment by kanaya23** [comment]
same, my account got banned, and it produce this error.

**Comment by ading2210** [comment]
I cannot reproduce this. Can you check if your IP has been banned?

**Comment by wangyu1997** [comment]
I don't think you ip has been banned.
First i receive the following response：
<img width="718" alt="image" src="https://github.com/ading2210/poe-api/assets/15991233/01b74d1a-a6a0-4438-a606-f5b00771ee8f">

when i retry some times, i got the response like first follow：
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com/. Retrying (4/10)..

I think the ip was banned cuz too many request， and i changed my ip，also get the first response。

**Comment by Akut0** [comment]
> I cannot reproduce this. Can you check if your IP has been banned?

I had the same error and changing the bot name to an shorter was working fine. But now im getting the same error on the edit part.

**Comment by CharlieCho2017** [comment]
> > I cannot reproduce this. Can you check if your IP has been banned?
> 
> I had the same error and changing the bot name to an shorter was working fine. But now im getting the same error on the edit part.
> 
> Seems like new variables have been added: { "botId": , "handle": "", "displayName": null, "description": "", "introduction": "", "isPromptPublic": true, "baseBot": "a2_2", "profilePictureUrl": "", "prompt": "", "apiUrl": null, "apiKey": null, "hasLinkification": false, "hasMarkdownRendering": true, "hasSuggestedReplies": true, "isPrivateBot": true, "temperature": null }

Could you create new bot now? I get the same error when I try to create a bot. My IP is not banned，because I can send message.

**Comment by yunlianwangluo** [comment]
some problem, just testing with samples/temporary_message.py:
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
seems poe.com reject the request from client, but it is normal in my browser with the same token

**Comment by leeeawa** [comment]
same problem

**Comment by CaoYunzhou** [comment]
change IP， you can `curl -I https://poe.com`  if status code == 403 , you IP block, i'm try other server ip

**Comment by ading2210** [comment]
This should have been fixed in v0.4.11.

**Comment by drmingdrmer** [comment]
I upgrade to v0.4.11 but the issue is not fixed.

I tried every of my proxy IP and got the same 403 response.

What do I do to find out what the problem is?

**Comment by ading2210** [comment]
I've removed the `Referrer`, `Origin`, and `Host` headers in the latest commit. 

I need someone to test to see if that is the cause of this issue by running `pip install git+https://github.com/ading2210/poe-api.git`.

**Comment by PoetGcc** [comment]
> I've removed the `Referrer`, `Origin`, and `Host` headers in the latest commit.
> 
> I need someone to test if this has fixed it by running `pip3 install git+https://github.com/ading2210/poe-api.git`.

it's worked.

**Comment by Shirasawaz** [comment]
> I've removed the `Referrer`, `Origin`, and `Host` headers in the latest commit.
> 
> I need someone to test if this has fixed it by running `pip3 install git+https://github.com/ading2210/poe-api.git`.

thank you, its worked.

**Comment by LiMingchen159** [comment]
> I've removed the `Referrer`, `Origin`, and `Host` headers in the latest commit.
> 
> I need someone to test if this has fixed it by running `pip3 install git+https://github.com/ading2210/poe-api.git`.

Thanks, worked fine for me

**Comment by monshizadeh** [comment]
> I've removed the `Referrer`, `Origin`, and `Host` headers in the latest commit.
> 
> I need someone to test if this has fixed it by running `pip3 install git+https://github.com/ading2210/poe-api.git`.

did not fix mine!

**Comment by ading2210** [comment]
Version 0.4.12 should have fixed this using the change in my previous comment.

**Comment by PaienNate** [comment]
> Version 0.4.12 should have fixed this using the change in my previous comment.

Actually I have the same wrong in 0.4.12 but using proxy to open the poe website seems okay.

**Comment by johnd0e** [comment]
Got the same issue on 0.5.2

**Comment by double-zinc** [comment]
i got the same issue on v0.5.2 too
have not been sending any request for the past 5 hours, and also tried using another IP/ token,
still got 430 response for client = poe.Client(...)

**Comment by Katiboo** [comment]
the same error on v0.5.2
RuntimeError: Failed to download https://poe.com/ too many times.

**Comment by maxinimus** [comment]
same error on v0.5.2 for several days

**Comment by ading2210** [comment]
@maxinimus @Katiboo see #218

**Comment by wdana-cn** [comment]
我大概能猜到为什么会被ban了，因为这个代理地址太多人使用会使得poe服务器接收到的大量的请求。被ban很正常，如果能够自己搭建一个代理地址应该就能解决🤓
